### ISSUE TITLE
LLVM 12

### ISSUE THREAD

**Issue by TheZoq2** [cdisselkoen/llvm-ir#11] opened 2021-06-14 08:23 UTC
It looks like LLVM 12 was released last month, do you have plans to update this library for it? I'd be happy to help out with the process if you'd like, but I might need some pointers to figure out what needs changing.

Looking at the LLVM-11 update, I suppose one needs to go through the changelog of llvm to find the things that need patching, or is there an easier way?

**Comment by cdisselkoen** [comment] 2021-06-14 15:31
Thanks for the ping, yes I do plan to update for LLVM 12.  As far as the process, it looks like `llvm-sys` has already released an LLVM 12 version, so I'll look at their changelog to see if corresponding updates need to be made here, and also I'll look at the general llvm changelog.

**Comment by cdisselkoen** [comment] 2021-06-16 04:27
Almost ready to go, but regression tests for the `SRet` parameter attribute are failing.  LLVM 12 changed it from a simple attribute to one that takes an argument, and for some reason the C API seems to be behaving in some way I'm not expecting for it.  Will keep investigating.

**Comment by cdisselkoen** [comment] 2021-06-21 22:27
Fixed in `071a74f` on `master` and in `2974c0a` on `0.7.x`.  Released as version `0.7.5` on crates.io.

**Closed by cdisselkoen** 2021-06-21 22:27 UTC

**Comment by TheZoq2** [comment] 2021-06-22 07:16
Awesome, thanks for the quick response :heart:
