### ISSUE TITLE
Support for LLVM 14?

### ISSUE THREAD

**Issue by woodruffw** [cdisselkoen/llvm-ir#18] opened 2022-04-22 14:40 UTC
First of all, thanks a ton for this crate!

`rustc` recently switched to LLVM 14, meaning that the IR produced by recent releases of `rustc` can't be consumed by this crate. 

I can take a stab at this in a couple of days, following the changes needed for LLVM 13: https://github.com/cdisselkoen/llvm-ir/commit/e6fc719e968db80e0d653f470f84466baf0fe89e

**Comment by cdisselkoen** [comment] 2022-05-11 00:45
I have the LLVM 14 support mostly ready to go, in theory (based on the observation that none of the official LLVM 13->14 changelog looks like it affects us).  But, I haven't run tests yet.  And in the past, there have often been changes that do affect us even if they do not make it into the official changelog.

I develop on macOS and the easiest way to test with LLVM 14 is via Homebrew.  Unfortunately, LLVM 14 has not yet shipped in Homebrew (https://github.com/Homebrew/homebrew-core/pull/97618).  Once it does, I will run regression tests, fix any issues that may come up, and release.

**Comment by imbrem** [comment] 2022-05-17 21:02
Have the issues with NSW and NUW flags been fixed in LLVM 14? I saw https://reviews.llvm.org/D89252, but I'm not sure how to interpret it haha

**Comment by cdisselkoen** [comment] 2022-05-20 04:11
No one with LLVM commit privileges has committed that patch, even though it is approved :/ if you or someone you know has committer privileges you can point them towards it!

**Comment by cdisselkoen** [comment] 2022-05-20 04:12
(that patch was created Oct 2020, it's been waiting a while)

**Comment by idavis** [comment] 2022-07-06 22:41
@cdisselkoen I believe LLVM 14 [has shipped in Homebrew](https://formulae.brew.sh/formula/llvm#default)

**Comment by cdisselkoen** [comment] 2022-08-28 18:57
Sorry for the long delay.  Just released v0.8.2 with support for LLVM 14

**Closed by cdisselkoen** 2022-08-28 18:57 UTC

**Comment by woodruffw** [comment] 2022-08-29 05:21
Thanks a ton!
